export const rulesData = [
  {
    id: 1,
    title: 'Postanowienia ogólne',
    content: [
      'Niniejszy Regulamin określa zasady udziału w Konkursie (jak zdefiniowano poniżej) oraz zasady jego przebiegu, nadzoru nad jego prawidłowym przeprowadzeniem oraz procesu reklamacyjnego (dalej: „Regulamin”).',
      'Konkurs prowadzony jest pod nazwą „Konkurs YSL | Opener” (dalej: „Konkurs”).',
      'Organizatorem Konkursu jest Kacper Osiecki, prowadzący działalność gospodarczą pod firmą: „ENYO KACPER OSIECKI” z siedzibą w Warszawie (adres: 00-819 Warszawa, ulica Złota numer 61 lokal 100), posiadającym numer NIP: 6141492391, REGON: 231094634, wpisany do Centralnej Ewidencji i Informacji o Działalności Gospodarczej Rzeczypospolitej Polskiej (CEiDG) (dalej: „Organizator”).',
      'Konkurs odbywa się na terenie Rzeczypospolitej Polskiej.',
      'Czas trwania konkursu, w tym czas przyjmowania zgłoszeń konkursowych z zastrzeżeniem § 1 ust. 6 oraz §6 ust. 1 obejmuje okres od dnia 24.05.2024 roku do końca dnia 09.06.2024 roku (tj: do godziny 23:59:59 włącznie).',
      'Czynności związane z przyznawaniem i odbiorem nagród oraz rozpatrywaniem reklamacji zakończą się do dnia 02.07.2024 roku.',
      'Fundatorem nagród jest Organizator Konkursu.',
      'Fundator zobowiązuje się ufundować nagrodę w Konkursie („Nagroda”) określoną szczegółowo w Regulaminie, które pozostawiona zostanie do dyspozycji Organizatora.',
      'Konkurs nie jest grą losową, loterią fantową, zakładem wzajemnym, loterią promocyjną, grą, której wynik zależy od przypadku, ani żadną inną w rozumieniu ustawy z dnia 19 listopada 2009 r. o grach hazardowych (t.j. Dz.U.2023.227). ',
      'Organizator jest składającym przyrzeczenie publiczne w rozumieniu art. 919 kodeksu cywilnego (t.j. Dz. U. z 2023 r. poz. 1610 z późn. zm.).',
      'Celem Konkursu jest nagrodzenie osoby, która najlepiej wykonała określone w ramach Konkursu zadanie konkursowe, na zasadach i warunkach określonych w niniejszym Regulaminie (dalej jako „Zadanie Konkursowe”).',
      'Udział w Konkursie jest dobrowolny. Uczestnik przed przystąpieniem do Konkursu powinien zapoznać się z treścią Regulaminu. ',
      'Uczestnik, przystępując do Konkursu, zobowiązuje się do przestrzegania zawartych w Regulaminie zasad, jak również potwierdza, iż spełnia wszystkie warunki, które uprawniają go do udziału w Konkursie.',
      'Dla uniknięcia wątpliwości Organizator wskazuje, że publikacja Zadania Konkursowego oznacza jednoczesną akceptację przez uczestnika postanowień Regulaminu.',
    ],
  },
  {
    id: 2,
    title: 'Zasady uczestnictwa w konkursie',
    content: [
      'Uczestnikiem niniejszego Konkursu może być osoba fizyczna, będąca konsumentem w rozumieniu art. 221 kodeksu cywilnego (t.j. Dz.U.2022.1360 z późn. zm.), która podczas trwania Konkursu spełnia następujące warunki: -	jest osobą pełnoletnią; -	posiada miejsce zamieszkania na terytorium Rzeczpospolitej Polskiej; -	posiada pełną zdolność do czynności prawnych; -	zaakceptowała postanowienia niniejszego Regulaminu (przez co rozumie się również publikację Zadania Konkursowego, bez wcześniejszego zgłoszenia zastrzeżeń co do postanowień Regulaminu); (dalej: „Uczestnik”).',
      'Zgłoszenie udziału w Konkursie musi być dokonane w sposób wskazany w Regulaminie. Niespełnienie któregokolwiek z warunków uczestnictwa spowoduje jego nieważność.',
      'W Konkursie można brać udział wyłącznie osobiście. Niedopuszczalne jest tworzenie kont i dokonywanie zgłoszeń konkursowych w imieniu osób trzecich. Organizator zastrzega, że w takich przypadkach Organizatorowi przysługuje prawo wykluczenia Uczestnika z Konkursu i odmowy przyznania mu Nagrody w Konkursie.',
      'Uczestnikami Konkursu nie mogą być pracownicy Organizatora, podmiotów działających na zlecenie Organizatora w związku z przeprowadzeniem Konkursu oraz członkowie rodzin tych osób. Za członków rodziny w rozumieniu niniejszego Regulaminu uznaje się: wstępnych, zstępnych, rodzeństwo, małżonków, a także osoby pozostające z ww. osobami w stosunku przysposobienia.',
    ],
  },
  {
    id: 3,
    title: 'Komisja konkursowa',
    content: [
      'Celem zapewnienia prawidłowej organizacji i przebiegu Konkursu, a w szczególności w celu dokonania oceny prawidłowości zgłoszeń do Konkursu, Organizator powoła komisję konkursową (dalej: „Komisja”). ',
      'W skład Komisji wejdą 3 (słownie: trzy) osoby wskazane przez Organizatora',
      'Komisja spośród Uczestników wyłoni dziesięć osób, które najlepiej wykonały Zadanie Konkursowe, a dokonując wyboru będzie kierowała się kryterium kreatywności oraz zgodności wykonania Zadania Konkursowego z Regulaminem.',
      'Osoby te zostaną zwycięzcami w Konkursie (dalej jako: „Zwycięzca” lub „Zwycięzcy”).',
      'Zostanie stworzona ponadto lista rezerwowa obejmująca 3 Uczestników, którzy w ocenie Komisji zasługują na wyróżnienie z uwagi na kreatywność wykonanego Zadania Konkursowego',
      'W przypadku, w którym którykolwiek ze Zwycięzców zostanie wykluczony z Konkursu z powodów wskazanych w §4 ust 2 Regulaminu, nie dostarczy danych niezbędnych do realizacji Nagrody, o których mowa w § 6 ust. 2 Regulaminu, nie wyrazi zgody na realizację Nagrody lub z innych przyczyn niemożliwa będzie jej realizacja, Organizator będzie kontaktować się z kolejnymi Uczestnikami z listy rezerwowej w celu powiadomienia ich o zwycięstwie w Konkursie.',
    ],
  },
  {
    id: 4,
    title: 'Zasady przeprowadzenia konkursu',
    content: [
      'Konkurs zostanie ogłoszony w ramach publikacji dokonanych w dniu 24.05.2024 roku przez: - twórcę – Hannę Puchalską, na prowadzonym przez nią profilu w serwisie społecznościowym TikTok, znajdującym się pod adresem: https://www.tiktok.com/@tojahania, -	twórcę – Maję Firek, na prowadzonym przez nią profilu w serwisie społecznościowym TikTok, znajdującym się pod adresem: https://www.tiktok.com/@majafirekk.',
      'W celu wzięcia udziału w Konkursie Uczestnik powinien w czasie jego trwania wykonać następujące Zadanie Konkursowe: Jakich kosmetyków YSL Beauty użyjesz do stworzenia festiwalowego makijażu i dlaczego?',
      'w kreatywny sposób odpowiedzieć na pytanie „Jakich kosmetyków YSL Beauty użyjesz do stworzenia festiwalowego makijażu i dlaczego?” w komentarzu pod postem konkursowym opublikowanym przez jednego z twórców wskazanych w § 4 ust. 1 Regulaminu,',
      'oznaczyć w wyżej wspominanym komentarzu: @yslbeauty, #yslbeautypoland #makeup #fragrance #yslbeautylightclub.',
      'Każdy Uczestnik może wziąć udział w Konkursie wyłącznie raz przez cały okres jego trwania.',
      'Organizator jest upoważniony do wykluczenia z Konkursu Uczestnika oraz usuwania z Konkursu wyników, w szczególności w następujących przypadkach: -	w przypadku, w którym Uczestnik nie posiada praw autorskich lub praw zależnych do Zadania Konkursowego i jego wszystkich elementów w zakresie wskazanym w Regulaminie; -	w przypadku naruszenia poprzez publikację Zadania Konkursowego jakichkolwiek praw osób trzecich, w tym w szczególności dóbr osobistych i praw autorskich osób trzecich; -	w przypadku, w którym wynik w Konkursie został uzyskany dzięki oszustwom wobec Organizatora lub innych Uczestników Konkursu; -	w przypadku: wykrycia działań związanych z uzyskaniem wyniku w sposób niezgodny z Regulaminem, w szczególności: próby wpływania na wyłonienie zwycięzcy w sposób niedozwolony, dokonywania zgłoszeń z wykorzystaniem fikcyjnych danych lub w imieniu osób trzecich, preparowania danych lub korzystania z dodatkowego oprogramowania w celu manipulowania wynikiem Konkursu; -	w przypadku, w którym opublikowane przez Uczestnika Zadanie Konkursowe zawiera wulgaryzmy, treści obraźliwe, polityczne, propagandowe, religijne lub treści sprzeczne z prawem.',
    ],
  },
  {
    id: 5,
    title: 'Nagrody',
    content: [
      'Nagrodami w Konkursie jest: -	10 x podwójny karnet na festiwal Opener Festiwal odbywający się w dniach 03-06.07.2024 r, -	10 x zakwaterowanie przez cały okres trwania festiwalu (tj. w terminie 03-06.07.2024 r.) w pokoju dwuosobowym w hotelu położonym w Gdańsku; nagroda obejmuje wyżywienie w ramach zakwaterowania w hotelu, -	10 x powitalny prezent niespodzianka od marki YSL czekający na Zwycięzcę w hotelu. Łączna wartość jednej Nagrody wynosi 2.650,00 złotych brutto, zaś łączna wartość wszystkich Nagród wynosi 26.500,00 złotych brutto.',
      'Nagroda nie obejmuje: wyżywienia na terenie samego festiwalu, kosztów związanych z transportem na trasie Gdańsk-Gdynia-Gdańsk oraz kosztów transportu do Gdańska i powrotu z Gdańska, które Zwycięzca zobowiązuje się pokryć we własnym zakresie. ',
      'Zwycięzcom, którzy otrzymają Nagrody Organizator przyzna dodatkowo nagrodę pieniężną, przeznaczoną na pokrycie kosztów podatku dochodowego od danej Nagrody. Wysokość dodatkowej nagrody pieniężnej stanowi 11,11% wartości danej Nagrody, przy czym kwota dodatkowej nagrody pieniężnej zostanie zaokrąglona do pełnego złotego w ten sposób, iż końcówka mniejsza niż 50 groszy zostanie pominięta, a końcówka równa lub większa od 50 groszy zostanie zaokrąglona w górę do pełnego złotego. ',
      'Podmiotem odpowiedzialnym za wydanie Nagród oraz odprowadzenie należnych podatków jest Organizator. Od łącznej wartości danej Nagrody oraz dodatkowej nagrody pieniężnej określonej powyżej, Organizator naliczy kwotę podatku zryczałtowanego zgodnie z przepisami ustawowymi. Kwota podatku zostanie odprowadzona przez Organizatora do właściwego Urzędu Skarbowego.',
      'Zwycięzcom Konkursu nie przysługuje prawo wymiany Nagrody na gotówkę ani na nagrodę innego rodzaju. Zwycięzcom nie przysługuje prawo zastrzegania szczególnych cech Nagrody (ani jej poszczególnych elementów). Wszystkie treści zawarte w materiałach reklamowo-promocyjnych dotyczących niniejszego Konkursu mają charakter poglądowy.',
      'Zwycięzca Konkursu nie może zrzec się części Nagrody, zrzeczenie się części Nagrody oznacza zrzeczenie się całości Nagrody. ',
      'Niewykorzystane Nagrody pozostaną w dyspozycji Organizatora.',
    ],
  },
  {
    id: 6,
    title: 'Powiadomienie o wygraniu',
    content: [
      'Wyłonienie Zwycięzcy nastąpi do dnia 15.06.2024 roku, zaś o swojej wygranej Zwycięzca zostanie powiadomiony poprzez odpowiedź Organizatora na pozostawiony przez niego komentarz w ramach Zadania Konkursowego (dalej: „Powiadomienie”).',
      'W następstwie otrzymania Powiadomienia Zwycięzca zobowiązany jest do wysłania w terminie najpóźniej do dnia 20.06.2024 roku, do godziny 23:59:59, na adres e-mail: konkurs@enyo.co danych osobowych Zwycięzcy oraz jego osoby towarzyszącej z którą ma zamiar wykorzystać otrzymaną Nagrodę, t.j. imię i nazwisko oraz adres e-mail. Wskazane dane zostaną udostępnione do hotelu oraz organizatora festiwalu Opener Festival w celu realizacji Nagrody',
      'Nagrody zostaną wydane zgodnie z obowiązującymi przepisami prawa podatkowego',
      'Organizator nie ponosi odpowiedzialności z powodu niemożności powiadomienia Zwycięzcy o jego wygranej z powodu zawieszenia bądź usunięcia prowadzonego przez niego profilu w serwisie społecznościowym TikTok.',
    ],
  },
  {
    id: 7,
    title: 'Ochrona danych osobowych',
    content: [
      'Administratorem Państwa danych osobowych jest Kacper Osiecki, prowadzący działalność gospodarczą pod firmą: „ENYO KACPER OSIECKI” z siedzibą w Warszawie (adres: 00-819 Warszawa, ulica Złota numer 61 lokal 100), posiadającym numer NIP: 6141492391, REGON: 231094634 (dalej „ENYO”). ',
      'We wszelkich sprawach związanych z przetwarzaniem Państwa danych osobowych przez ENYO prosimy o kontakt pod adresem email: rodo@enyo.co lub na adres wskazany w ust. 1 z dopiskiem „dane osobowe – Konkurs YSL | Opener” ',
      'W związku z Państwa uczestnictwem w Konkursie zbieramy następujące Państwa dane osobowe: -	imię, nazwisko,-	nazwę profilu w serwisie społecznościowym; -	adres e-mail – w przypadku Zwycięzcy,-	dane niezbędne do wykonania obowiązków związanych z zapłatą podatku dochodowego – w przypadku Zwycięzcy,',
      'Państwa dane osobowe przetwarzane będą̨ w celu: -	zgłoszenia i udziału w Konkursie oraz wyłonienia oraz ogłoszenia Zwycięzcy Konkursu - na podstawie zgody udzielonej poprzez opublikowanie zgłoszenia do Konkursu (art. 6 ust. 1 lit. a RODO), przez okres trwania Konkursu do momentu jego rozstrzygnięcia, -	obsługi wysyłki Nagrody - na podstawie prawnie uzasadnionego interesu Administratora (art. 6 ust. 1 lit. f RODO), przez okres niezbędny do zrealizowania wysyłki Nagród,-	rozpatrzenia reklamacji - na podstawie prawnie uzasadnionego interesu Administratora (art. 6 ust. 1 lit. f RODO), przez okres trwania postępowania reklamacyjnego,-	w przypadku wygranej w Konkursie i otrzymania Nagrody, w celach podatkowych i rachunkowych - na podstawie przepisów ustawy Ordynacja podatkowa i ustawy o rachunkowości (art. 6 ust. 1 lit. c RODO), przez okres wymagany przez te przepisy.',
      'Z uwagi na zapewnienie odpowiedniej organizacji w bieżących sprawach dotyczących organizacji i przeprowadzenia Konkursu odbiorcą Państwa danych osobowych mogą̨ być́: -	dostawcy usług prawnych i doradczych wspierających ENYO w dochodzeniu należytych roszczeń́ (w szczególności kancelarie prawne, firmy windykacyjne); -	dostawcy usług zaopatrujących ENYO w rozwiązania techniczne oraz organizacyjne, wspierających procesy biznesowe (w szczególności dostawcy usług informatycznych, firmy kurierskie i pocztowe) działające na zlecenie ENYO na podstawie stosownych umów lub przepisów prawa. ',
      'Państwa dane osobowe nie będą przekazywane poza obszar Unii Europejskiej. Taka sytuacja może jednak mieć miejsce w związku z korzystaniem z rozwiązań chmurowych oraz ze zlecaniem wykonania określonych usług/działań podmiotom mającym siedzibę poza EOG lub przetwarzającym dane poza EOG (tymi podmiotami może być np. dostawca oprogramowania/portale społecznościowe). Dane osobowe mogą być przekazane do państw trzecich (państwa poza EOG) lub podmiotów w państwach trzecich, w stosunku do których Komisja Europejska stwierdziła odpowiedni stopień ochrony danych, zastosowano w umowach z tymi podmiotami standardowe klauzule ochrony danych lub zastosowano odpowiednie inne zabezpieczenia, o których mowa w powszechnie obowiązujących przepisach prawa.',
      'Państwa dane osobowe będą̨ przetwarzane w czasie trwania Konkursu oraz po jego zakończeniu w okresie niezbędnym do przekazania Nagrody lub wygaśnięcia roszczeń/reklamacji. Po upływie tych terminów Państwa dane będą usuwane lub poddawane anonimizacji. ',
      'Przysługuje Państwu, jako Uczestnikom Konkursu, prawo dostępu do treści Państwa danych, ich sprostowania, żądania ich usunięcia lub ograniczenia przetwarzania, ich przenoszenia do innego administratora oraz wniesienia sprzeciwu wobec ich przetwarzania. W przypadku potrzeby skorzystania z tych uprawnień prosimy o kontakt wskazany w ust. 2 powyżej. Informujemy także, że przysługuje Państwu prawo wniesienia skargi do organu nadzorującego przestrzeganie przepisów ochrony danych osobowych, tj. Prezesa Urzędu Ochrony Danych Osobowych (ul. Stawki 2, 00-193 Warszawa). ',
      'Podanie przez Państwa danych osobowych jest dobrowolne, aczkolwiek niezbędne do uczestnictwa w Konkursie. ',
      'Dalsze przetwarzanie danych osobowych Zwycięzców Konkursu w celach marketingowych może wiązać́ się z koniecznością podpisania przez nich dodatkowych, odpowiednich dokumentów. ',
      'ENYO oświadcza, że poważnie traktuje swoje zobowiązanie do zgodnego z prawem przetwarzania danych osobowych Uczestników Konkursu. ENYO w stosunkach z Uczestnikami będzie działać́ zgodnie z przyjętymi standardami w zakresie ochrony danych osobowych, ze szczególnym uwzględnieniem praw i interesów Uczestników. ',
      'Państwa dane nie będą̨ przetwarzane w sposób zautomatyzowany, w tym nie będą̨ profilowane. ',
      'W każdym momencie możecie Państwo dokonać wycofania złożonej wcześniej zgody poprzez przesłanie stosownego oświadczenia na adres email: rodo@enyo.co. Wycofanie zgody nie wpływa na zgodność́ z prawem przetwarzania danych, którego dokonano na jej podstawie przed jej wycofaniem.',
    ],
  },
  {
    id: 8,
    title: 'Prawa autorskie',
    content: [
      'Uczestnicy mogą zgłaszać do Konkursu wyłącznie treści własnego autorstwa. Organizator jest upoważniony do weryfikacji w każdym czasie treści, z uwzględnieniem kryterium autorstwa. W razie stwierdzenia naruszeń niniejszego zapisu, Organizator jest uprawniony do wykluczenia Uczestnika dopuszczającego się naruszeń na każdym etapie Konkursu. Uprawnienie do wykluczenia Uczestnika obejmuje również prawo do pozbawiania Uczestnika Nagrody. W takim przypadku Uczestnik ma prawo złożenia reklamacji zgodnie z Regulaminem.',
      'Uczestnik ponosi wyłączną odpowiedzialność za naruszenie autorskich praw majątkowych lub  autorskich praw osobistych osób trzecich w związku z opublikowanym Zadaniem Konkursowym. Uczestnik zobowiązuje się zwrócić Organizatorowi wszelkie koszty, jakie poniósł Organizator w związku z naruszeniem praw lub dóbr osób trzecich na skutek eksploatacji wadliwej treści dostarczonej przez Uczestnika.',
      'Uczestnik może zostać wykluczony z Konkursu w każdym czasie w razie stwierdzenia przez Komisję Konkursową, że jego zgłoszenie konkursowe nie spełnia wymogów Regulaminu lub w przypadku zgłoszenia do Organizatora przez osoby trzecie roszczeń związanych ze zgłoszeniem. W takim przypadku Uczestnik ma prawo złożenia reklamacji zgodnie z Regulaminem.',
    ],
  },
  {
    id: 9,
    title: 'Postępowanie reklamacyjne',
    content: [
      'Wszelkie reklamacje dotyczące sposobu przeprowadzania Konkursu Uczestnicy winni zgłaszać w czasie trwania Konkursu oraz nie później niż do 5 dni roboczych od terminu Powiadomienia na piśmie lub poprzez wysłanie wiadomości na adres email: contact@enyo.co (o zachowaniu terminu decyduje data stempla pocztowego/serwera odbierającego wiadomość).',
      'Reklamacja powinna zawierać imię, nazwisko, adres zamieszkania (w przypadku zgłoszenia reklamacji w formie pisemnej) oraz dokładny opis i wskazanie przyczyny reklamacji oraz żądanie Uczestnika. ',
      'Reklamacja powinna być przesłana na adres bądź adres e-mail Organizatora z dopiskiem „Konkurs YSL | Opener”.',
      'Reklamacje rozpatrywane będą pisemnie w terminie do 5 dni roboczych od daty ich otrzymania.',
      'Uczestnik zgłaszający reklamację otrzyma decyzję Komisji Konkursowej w formie w jakiej złożona została przez niego reklamacja.',
      'Postępowanie reklamacyjne jest dobrowolne i nie wyłącza prawa Uczestnika do niezależnego dochodzenia swoich roszczeń na drodze postępowania sądowego.',
    ],
  },
  {
    id: 10,
    title: 'Postanowienia końcowe',
    content: [
      'Regulamin Konkursu dostępny jest w siedzibie Organizatora.',
      'Organizator oświadcza, że portal społecznościowy TikTok nie jest organizatorem ani współorganizatorem Konkursu. Konkurs nie jest również w żaden sposób sponsorowany, popierany, zarządzany ani powiązany z podmiotami będącymi właścicielami portalu TikTok. Portal TikTok nie ponosi odpowiedzialności za przeprowadzenie Konkursu, a w szczególności za realizację Nagród.',
      'Organizator zastrzega sobie prawo zmiany Regulaminu, o ile nie spowoduje to pogorszenia warunków Uczestnika oraz zasad uczestnictwa w Konkursie, w szczególności zastrzega sobie prawo do wydłużenia okresu trwania Konkursu. W przypadku zmiany Regulaminu, informacja o zmianie oraz link do nowego Regulaminu zostaną przesłane do Uczestników w formie wiadomości prywatnej w taki sposób, że każdy Uczestnik będzie miał do niego dostęp.',
      'W kwestiach nieuregulowanych niniejszym Regulaminem stosuje się przepisy prawa powszechnie obowiązującego, w tym przede wszystkim przepisy Kodeksu cywilnego.',
      'O dotrzymaniu terminu nadesłania wiadomości, informacji, korespondencji lub innej przesyłki przewidzianej Regulaminem decydować będzie data nadania, chyba że inaczej zastrzeżono w treści niniejszego Regulaminu.',
      'Regulamin wchodzi w życie z dniem 24.05.2024 r.',
    ],
  },
];
